name: edumate
description: A new Flutter project.

publish_to: "none"


version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.00"

  # http: ^0.13.5
dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  bloc: ^8.1.1
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^2.0.4
  cached_network_image: 3.3.1
  form_field_validator: ^1.1.0
  google_fonts: ^4.0.3
  http: ^1.1.0
  flip_card: ^0.7.0
  image_picker: ^0.8.7+1
  permission_handler: ^10.2.0
  pin_code_fields: ^7.4.0
  photo_manager: ^3.6.3
  carousel_slider: ^4.2.1
  shimmer: ^2.0.0
  timeago: ^3.4.0
  socket_io_client: ^1.0.2
  equatable: ^2.0.5
  url_launcher: ^6.2.2
  sliding_top_panel: ^0.0.7
  cached_network_image_web: 1.1.1
  rxdart: ^0.27.1
  google_mlkit_text_recognition: ^0.11.0
  google_mlkit_entity_extraction: ^0.11.0
  image_editor_plus: ^0.2.3
  camera: ^0.10.5+9
  flutter_animate: ^4.5.0
  image: ^4.1.7
  flutter_local_notifications: ^16.3.3
  timezone: ^0.9.1
  sqflite: ^2.2.8
  path: ^1.8.2
  file_picker: ^5.0.0
  dotted_border: ^2.0.0
  # flutter_pdfview: ^1.3.0
  # path_provider: ^2.0.11
  # open_file: ^3.3.2
  # dio: ^5.1.2


dev_dependencies:
  icons_launcher: ^2.1.6
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

icons_launcher:
  image_path: "assets/img/logo-white.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/asset/illustrations/
    - assets/asset/badges/
    - assets/asset/fonts/
    - assets/asset/images/
    - assets/asset/logos/
    - assets/asset/certificates/
    - assets/asset/icons/
    - assets/svg/
    - assets/img/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
    # cached_network_image: ^3.2.3  cached_network_image: ^3.3.1
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SF Pro Text
      fonts:
        - asset: assets/asset/fonts/SFProText-Regular.ttf
        - asset: assets/asset/fonts/SFProText-Bold.ttf
          weight: 800
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
